# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2

jobs:
  build-and-push-image-and-run:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - gcp-cloud-run/init
      - gcp-cloud-run/build:
          tag: 'gcr.io/${GOOGLE_PROJECT_ID}/todoist-discord-bot-<< pipeline.git.branch >>-${CIRCLE_SHA1}'
      - gcp-cloud-run/deploy:
          image: 'gcr.io/${GOOGLE_PROJECT_ID}/todoist-discord-bot-<< pipeline.git.branch >>-${CIRCLE_SHA1}'
          platform: managed
          region: europe-west1
          service-name: todoist-discord-bot-<< pipeline.git.branch >>
          unauthenticated: true

workflows:
  test-build-deploy:
    jobs:
      - gradle/test
      - build-and-push-image-and-run:
          filters:
            branches:
              only:
                - test
